//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geometry
{
    [Serializable]
    public class AccelStampedMsg : Message
    {
        public const string k_RosMessageName = "geometry_msgs/AccelStamped";
        public override string RosMessageName => k_RosMessageName;

        //  An accel with reference coordinate frame and timestamp
        public Std.HeaderMsg header;
        public AccelMsg accel;

        public AccelStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.accel = new AccelMsg();
        }

        public AccelStampedMsg(Std.HeaderMsg header, AccelMsg accel)
        {
            this.header = header;
            this.accel = accel;
        }

        public static AccelStampedMsg Deserialize(MessageDeserializer deserializer) => new AccelStampedMsg(deserializer);

        private AccelStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.accel = AccelMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.accel);
        }

        public override string ToString()
        {
            return "AccelStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\naccel: " + accel.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
