//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geometry
{
    [Serializable]
    public class InertiaStampedMsg : Message
    {
        public const string k_RosMessageName = "geometry_msgs/InertiaStamped";
        public override string RosMessageName => k_RosMessageName;

        //  An Inertia with a time stamp and reference frame.
        public Std.HeaderMsg header;
        public InertiaMsg inertia;

        public InertiaStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.inertia = new InertiaMsg();
        }

        public InertiaStampedMsg(Std.HeaderMsg header, InertiaMsg inertia)
        {
            this.header = header;
            this.inertia = inertia;
        }

        public static InertiaStampedMsg Deserialize(MessageDeserializer deserializer) => new InertiaStampedMsg(deserializer);

        private InertiaStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.inertia = InertiaMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.inertia);
        }

        public override string ToString()
        {
            return "InertiaStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\ninertia: " + inertia.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
