//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Geometry
{
    public class MPolygonStamped : Message
    {
        public const string RosMessageName = "geometry_msgs/PolygonStamped";

        //  This represents a Polygon with reference coordinate frame and timestamp
        public MHeader header;
        public MPolygon polygon;

        public MPolygonStamped()
        {
            this.header = new MHeader();
            this.polygon = new MPolygon();
        }

        public MPolygonStamped(MHeader header, MPolygon polygon)
        {
            this.header = header;
            this.polygon = polygon;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.AddRange(polygon.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            offset = this.polygon.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MPolygonStamped: " +
            "\nheader: " + header.ToString() +
            "\npolygon: " + polygon.ToString();
        }
    }
}
