//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Geometry
{
    public class MPoseArray : Message
    {
        public const string RosMessageName = "geometry_msgs/PoseArray";

        //  An array of poses with a header for global reference.
        public MHeader header;
        public MPose[] poses;

        public MPoseArray()
        {
            this.header = new MHeader();
            this.poses = new MPose[0];
        }

        public MPoseArray(MHeader header, MPose[] poses)
        {
            this.header = header;
            this.poses = poses;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());

            listOfSerializations.Add(BitConverter.GetBytes(poses.Length));
            foreach (var entry in poses)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);

            var posesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.poses = new MPose[posesArrayLength];
            for (var i = 0; i < posesArrayLength; i++)
            {
                this.poses[i] = new MPose();
                offset = this.poses[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MPoseArray: " +
            "\nheader: " + header.ToString() +
            "\nposes: " + System.String.Join(", ", poses.ToList());
        }
    }
}
