//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geometry
{
    [Serializable]
    public class PointStampedMsg : Message
    {
        public const string k_RosMessageName = "geometry_msgs/PointStamped";
        public override string RosMessageName => k_RosMessageName;

        //  This represents a Point with reference coordinate frame and timestamp
        public Std.HeaderMsg header;
        public PointMsg point;

        public PointStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.point = new PointMsg();
        }

        public PointStampedMsg(Std.HeaderMsg header, PointMsg point)
        {
            this.header = header;
            this.point = point;
        }

        public static PointStampedMsg Deserialize(MessageDeserializer deserializer) => new PointStampedMsg(deserializer);

        private PointStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.point = PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.point);
        }

        public override string ToString()
        {
            return "PointStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\npoint: " + point.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
