//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geometry
{
    [Serializable]
    public class WrenchMsg : Message
    {
        public const string k_RosMessageName = "geometry_msgs/Wrench";
        public override string RosMessageName => k_RosMessageName;

        //  This represents force in free space, separated into its linear and angular parts.
        public Vector3Msg force;
        public Vector3Msg torque;

        public WrenchMsg()
        {
            this.force = new Vector3Msg();
            this.torque = new Vector3Msg();
        }

        public WrenchMsg(Vector3Msg force, Vector3Msg torque)
        {
            this.force = force;
            this.torque = torque;
        }

        public static WrenchMsg Deserialize(MessageDeserializer deserializer) => new WrenchMsg(deserializer);

        private WrenchMsg(MessageDeserializer deserializer)
        {
            this.force = Vector3Msg.Deserialize(deserializer);
            this.torque = Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.force);
            serializer.Write(this.torque);
        }

        public override string ToString()
        {
            return "WrenchMsg: " +
            "\nforce: " + force.ToString() +
            "\ntorque: " + torque.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
