//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav
{
    [Serializable]
    public class GridCellsMsg : Message
    {
        public const string k_RosMessageName = "nav_msgs/GridCells";
        public override string RosMessageName => k_RosMessageName;

        //  An array of cells in a 2D grid
        public Std.HeaderMsg header;
        //  Width of each cell
        public float cell_width;
        //  Height of each cell
        public float cell_height;
        //  Each cell is represented by the Point at the center of the cell
        public Geometry.PointMsg[] cells;

        public GridCellsMsg()
        {
            this.header = new Std.HeaderMsg();
            this.cell_width = 0.0f;
            this.cell_height = 0.0f;
            this.cells = new Geometry.PointMsg[0];
        }

        public GridCellsMsg(Std.HeaderMsg header, float cell_width, float cell_height, Geometry.PointMsg[] cells)
        {
            this.header = header;
            this.cell_width = cell_width;
            this.cell_height = cell_height;
            this.cells = cells;
        }

        public static GridCellsMsg Deserialize(MessageDeserializer deserializer) => new GridCellsMsg(deserializer);

        private GridCellsMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.cell_width);
            deserializer.Read(out this.cell_height);
            deserializer.Read(out this.cells, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.cell_width);
            serializer.Write(this.cell_height);
            serializer.WriteLength(this.cells);
            serializer.Write(this.cells);
        }

        public override string ToString()
        {
            return "GridCellsMsg: " +
            "\nheader: " + header.ToString() +
            "\ncell_width: " + cell_width.ToString() +
            "\ncell_height: " + cell_height.ToString() +
            "\ncells: " + System.String.Join(", ", cells.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
