//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Nav
{
    public class MPath : Message
    {
        public const string RosMessageName = "nav_msgs/Path";

        // An array of poses that represents a Path for a robot to follow
        public MHeader header;
        public Geometry.MPoseStamped[] poses;

        public MPath()
        {
            this.header = new MHeader();
            this.poses = new Geometry.MPoseStamped[0];
        }

        public MPath(MHeader header, Geometry.MPoseStamped[] poses)
        {
            this.header = header;
            this.poses = poses;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());

            listOfSerializations.Add(BitConverter.GetBytes(poses.Length));
            foreach (var entry in poses)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);

            var posesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.poses = new Geometry.MPoseStamped[posesArrayLength];
            for (var i = 0; i < posesArrayLength; i++)
            {
                this.poses[i] = new Geometry.MPoseStamped();
                offset = this.poses[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MPath: " +
            "\nheader: " + header.ToString() +
            "\nposes: " + System.String.Join(", ", poses.ToList());
        }
    }
}
