//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Nav
{
    [Serializable]
    public class OccupancyGridMsg : Message
    {
        public const string k_RosMessageName = "nav_msgs/OccupancyGrid";

        //  This represents a 2-D grid map, in which each cell represents the probability of
        //  occupancy.
        public HeaderMsg header;
        // MetaData for the map
        public MapMetaDataMsg info;
        //  The map data, in row-major order, starting with (0,0).  Occupancy
        //  probabilities are in the range [0,100].  Unknown is -1.
        public sbyte[] data;

        public OccupancyGridMsg()
        {
            this.header = new HeaderMsg();
            this.info = new MapMetaDataMsg();
            this.data = new sbyte[0];
        }

        public OccupancyGridMsg(HeaderMsg header, MapMetaDataMsg info, sbyte[] data)
        {
            this.header = header;
            this.info = info;
            this.data = data;
        }

        public static OccupancyGridMsg Deserialize(MessageDeserializer deserializer) => new OccupancyGridMsg(deserializer);

        private OccupancyGridMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.info = MapMetaDataMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, sizeof(sbyte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.info);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "OccupancyGridMsg: " +
            "\nheader: " + header.ToString() +
            "\ninfo: " + info.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

        #if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
        #else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
        #endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
