//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityInterfaces
{
    [Serializable]
    public class RosUnityTopicListRequest : Message
    {
        public const string k_RosMessageName = "unity_interfaces/RosUnityTopicList";



        public RosUnityTopicListRequest()
        {
        }
        public RosUnityTopicListRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "RosUnityTopicListRequest: ";
        }

        public static RosUnityTopicListRequest Deserialize(MessageDeserializer deserializer)
        {
            return new RosUnityTopicListRequest(deserializer);
        }

        #if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
        #else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
        #endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
