//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Visualization
{
    [Serializable]
    public class InteractiveMarkerPoseMsg : Message
    {
        public const string k_RosMessageName = "visualization_msgs/InteractiveMarkerPose";
        public override string RosMessageName => k_RosMessageName;

        //  Time/frame info.
        public Std.HeaderMsg header;
        //  Initial pose. Also, defines the pivot point for rotations.
        public Geometry.PoseMsg pose;
        //  Identifying string. Must be globally unique in
        //  the topic that this message is sent through.
        public string name;

        public InteractiveMarkerPoseMsg()
        {
            this.header = new Std.HeaderMsg();
            this.pose = new Geometry.PoseMsg();
            this.name = "";
        }

        public InteractiveMarkerPoseMsg(Std.HeaderMsg header, Geometry.PoseMsg pose, string name)
        {
            this.header = header;
            this.pose = pose;
            this.name = name;
        }

        public static InteractiveMarkerPoseMsg Deserialize(MessageDeserializer deserializer) => new InteractiveMarkerPoseMsg(deserializer);

        private InteractiveMarkerPoseMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.pose);
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "InteractiveMarkerPoseMsg: " +
            "\nheader: " + header.ToString() +
            "\npose: " + pose.ToString() +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
