//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Octomap
{
    public class BoundingBoxQueryRequest : Message
    {
        public const string RosMessageName = "octomap_msgs-melodic-devel/BoundingBoxQuery";

        //  Clear a region specified by a global axis-aligned bounding box in stored OctoMap
        //  minimum corner point of axis-aligned bounding box in global frame
        public Geometry.Point min;
        //  maximum corner point of axis-aligned bounding box in global frame
        public Geometry.Point max;

        public BoundingBoxQueryRequest()
        {
            this.min = new Geometry.Point();
            this.max = new Geometry.Point();
        }

        public BoundingBoxQueryRequest(Geometry.Point min, Geometry.Point max)
        {
            this.min = min;
            this.max = max;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(min.SerializationStatements());
            listOfSerializations.AddRange(max.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.min.Deserialize(data, offset);
            offset = this.max.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "BoundingBoxQueryRequest: " +
            "\nmin: " + min.ToString() +
            "\nmax: " + max.ToString();
        }
    }
}
