//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Shape
{
    [Serializable]
    public class MeshMsg : Message
    {
        public const string k_RosMessageName = "shape_msgs/Mesh";
        public override string RosMessageName => k_RosMessageName;

        //  Definition of a mesh.
        //  List of triangles; the index values refer to positions in vertices[].
        public MeshTriangleMsg[] triangles;
        //  The actual vertices that make up the mesh.
        public Geometry.PointMsg[] vertices;

        public MeshMsg()
        {
            this.triangles = new MeshTriangleMsg[0];
            this.vertices = new Geometry.PointMsg[0];
        }

        public MeshMsg(MeshTriangleMsg[] triangles, Geometry.PointMsg[] vertices)
        {
            this.triangles = triangles;
            this.vertices = vertices;
        }

        public static MeshMsg Deserialize(MessageDeserializer deserializer) => new MeshMsg(deserializer);

        private MeshMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.triangles, MeshTriangleMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.vertices, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.triangles);
            serializer.Write(this.triangles);
            serializer.WriteLength(this.vertices);
            serializer.Write(this.vertices);
        }

        public override string ToString()
        {
            return "MeshMsg: " +
            "\ntriangles: " + System.String.Join(", ", triangles.ToList()) +
            "\nvertices: " + System.String.Join(", ", vertices.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
