//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Shape
{
    [Serializable]
    public class MeshTriangleMsg : Message
    {
        public const string k_RosMessageName = "shape_msgs/MeshTriangle";
        public override string RosMessageName => k_RosMessageName;

        //  Definition of a triangle's vertices.
        public uint[] vertex_indices;

        public MeshTriangleMsg()
        {
            this.vertex_indices = new uint[3];
        }

        public MeshTriangleMsg(uint[] vertex_indices)
        {
            this.vertex_indices = vertex_indices;
        }

        public static MeshTriangleMsg Deserialize(MessageDeserializer deserializer) => new MeshTriangleMsg(deserializer);

        private MeshTriangleMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.vertex_indices, sizeof(uint), 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.vertex_indices);
        }

        public override string ToString()
        {
            return "MeshTriangleMsg: " +
            "\nvertex_indices: " + System.String.Join(", ", vertex_indices.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
