//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Shape
{
    [Serializable]
    public class PlaneMsg : Message
    {
        public const string k_RosMessageName = "shape_msgs/Plane";
        public override string RosMessageName => k_RosMessageName;

        //  Representation of a plane, using the plane equation ax + by + cz + d = 0.
        // 
        //  a := coef[0]
        //  b := coef[1]
        //  c := coef[2]
        //  d := coef[3]
        public double[] coef;

        public PlaneMsg()
        {
            this.coef = new double[4];
        }

        public PlaneMsg(double[] coef)
        {
            this.coef = coef;
        }

        public static PlaneMsg Deserialize(MessageDeserializer deserializer) => new PlaneMsg(deserializer);

        private PlaneMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.coef, sizeof(double), 4);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.coef);
        }

        public override string ToString()
        {
            return "PlaneMsg: " +
            "\ncoef: " + System.String.Join(", ", coef.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
