//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.ObjectRecognition
{
    [Serializable]
    public class TableArrayMsg : Message
    {
        public const string k_RosMessageName = "object_recognition_msgs/TableArray";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        //  Just an array of tables
        public TableMsg[] tables;

        public TableArrayMsg()
        {
            this.header = new HeaderMsg();
            this.tables = new TableMsg[0];
        }

        public TableArrayMsg(HeaderMsg header, TableMsg[] tables)
        {
            this.header = header;
            this.tables = tables;
        }

        public static TableArrayMsg Deserialize(MessageDeserializer deserializer) => new TableArrayMsg(deserializer);

        private TableArrayMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.tables, TableMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.tables);
            serializer.Write(this.tables);
        }

        public override string ToString()
        {
            return "TableArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\ntables: " + System.String.Join(", ", tables.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
