//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tf2
{
    [Serializable]
    public class LookupTransformFeedback : Message
    {
        public const string k_RosMessageName = "tf2_msgs/LookupTransform";
        public override string RosMessageName => k_RosMessageName;


        public LookupTransformFeedback()
        {
        }
        public static LookupTransformFeedback Deserialize(MessageDeserializer deserializer) => new LookupTransformFeedback(deserializer);

        private LookupTransformFeedback(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "LookupTransformFeedback: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
