//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Std
{
    public class MSetBoolResponse : Message
    {
        public const string k_RosMessageName = "std_srvs/SetBool";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        //  indicate successful run of triggered service
        public string message;
        //  informational, e.g. for error messages

        public MSetBoolResponse()
        {
            this.success = false;
            this.message = "";
        }

        public MSetBoolResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.success));
            listOfSerializations.Add(SerializeString(this.message));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.success = BitConverter.ToBoolean(data, offset);
            offset += 1;
            var messageStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.message = DeserializeString(data, offset, messageStringBytesLength);
            offset += messageStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MSetBoolResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        static void OnLoad()
        {
            MessageRegistry.Register<MSetBoolResponse>(k_RosMessageName);
        }
    }
}
