//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geometry
{
    public class Wrench : Message
    {
        public const string RosMessageName = "geometry_msgs/Wrench";

        //  This represents force in free space, separated into
        //  its linear and angular parts.
        public Vector3 force;
        public Vector3 torque;

        public Wrench()
        {
            this.force = new Vector3();
            this.torque = new Vector3();
        }

        public Wrench(Vector3 force, Vector3 torque)
        {
            this.force = force;
            this.torque = torque;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(force.SerializationStatements());
            listOfSerializations.AddRange(torque.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.force.Deserialize(data, offset);
            offset = this.torque.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "Wrench: " +
            "\nforce: " + force.ToString() +
            "\ntorque: " + torque.ToString();
        }
    }
}
