//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Diagnostic
{
    [Serializable]
    public class AddDiagnosticsResponse : Message
    {
        public const string k_RosMessageName = "diagnostic_msgs/AddDiagnostics";
        public override string RosMessageName => k_RosMessageName;

        //  True if diagnostic aggregator was updated with new diagnostics, False
        //  otherwise. A false return value means that either there is a bond in the
        //  aggregator which already used the requested namespace, or the initialization
        //  of analyzers failed.
        public bool success;
        //  Message with additional information about the success or failure
        public string message;

        public AddDiagnosticsResponse()
        {
            this.success = false;
            this.message = "";
        }

        public AddDiagnosticsResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }

        public static AddDiagnosticsResponse Deserialize(MessageDeserializer deserializer) => new AddDiagnosticsResponse(deserializer);

        private AddDiagnosticsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "AddDiagnosticsResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
