//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Diagnostic
{
    [Serializable]
    public class SelfTestResponse : Message
    {
        public const string k_RosMessageName = "diagnostic_msgs/SelfTest";
        public override string RosMessageName => k_RosMessageName;

        public string id;
        public sbyte passed;
        public DiagnosticStatusMsg[] status;

        public SelfTestResponse()
        {
            this.id = "";
            this.passed = 0;
            this.status = new DiagnosticStatusMsg[0];
        }

        public SelfTestResponse(string id, sbyte passed, DiagnosticStatusMsg[] status)
        {
            this.id = id;
            this.passed = passed;
            this.status = status;
        }

        public static SelfTestResponse Deserialize(MessageDeserializer deserializer) => new SelfTestResponse(deserializer);

        private SelfTestResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.passed);
            deserializer.Read(out this.status, DiagnosticStatusMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.passed);
            serializer.WriteLength(this.status);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "SelfTestResponse: " +
            "\nid: " + id.ToString() +
            "\npassed: " + passed.ToString() +
            "\nstatus: " + System.String.Join(", ", status.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
