//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav
{
    public class LoadMapRequest : Message
    {
        public const string RosMessageName = "nav_msgs/LoadMap";

        //  URL of map resource
        //  Can be an absolute path to a file: file:///path/to/maps/floor1.yaml
        //  Or, relative to a ROS package: package://my_ros_package/maps/floor2.yaml
        public string map_url;

        public LoadMapRequest()
        {
            this.map_url = "";
        }

        public LoadMapRequest(string map_url)
        {
            this.map_url = map_url;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.map_url));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var map_urlStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.map_url = DeserializeString(data, offset, map_urlStringBytesLength);
            offset += map_urlStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "LoadMapRequest: " +
            "\nmap_url: " + map_url.ToString();
        }
    }
}
