//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav
{
    public class SetMapRequest : Message
    {
        public const string RosMessageName = "nav_msgs/SetMap";

        //  Set a new map together with an initial pose
        public OccupancyGrid map;
        public Geometry.PoseWithCovarianceStamped initial_pose;

        public SetMapRequest()
        {
            this.map = new OccupancyGrid();
            this.initial_pose = new Geometry.PoseWithCovarianceStamped();
        }

        public SetMapRequest(OccupancyGrid map, Geometry.PoseWithCovarianceStamped initial_pose)
        {
            this.map = map;
            this.initial_pose = initial_pose;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(map.SerializationStatements());
            listOfSerializations.AddRange(initial_pose.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.map.Deserialize(data, offset);
            offset = this.initial_pose.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "SetMapRequest: " +
            "\nmap: " + map.ToString() +
            "\ninitial_pose: " + initial_pose.ToString();
        }
    }
}
