//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tf2
{
    [Serializable]
    public class FrameGraphRequest : Message
    {
        public const string k_RosMessageName = "tf2_msgs/FrameGraph";
        public override string RosMessageName => k_RosMessageName;


        public FrameGraphRequest()
        {
        }
        public static FrameGraphRequest Deserialize(MessageDeserializer deserializer) => new FrameGraphRequest(deserializer);

        private FrameGraphRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "FrameGraphRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
