//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityInterfaces
{
    [Serializable]
    public class RosUnitySrvMessageMsg : Message
    {
        public const string k_RosMessageName = "unity_interfaces/RosUnitySrvMessage";


        public int srv_id;
        public bool is_request;
        public string topic;
        public byte[] payload;

        public RosUnitySrvMessageMsg()
        {
            this.srv_id = 0;
            this.is_request = false;
            this.topic = "";
            this.payload = new byte[0];
        }

        public RosUnitySrvMessageMsg(int srv_id, bool is_request, string topic, byte[] payload)
        {
            this.srv_id = srv_id;
            this.is_request = is_request;
            this.topic = topic;
            this.payload = payload;
        }

        public RosUnitySrvMessageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.srv_id);
            deserializer.Read(out this.is_request);
            deserializer.Read(out this.topic);
            deserializer.Read(out this.payload, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.srv_id);
            serializer.Write(this.is_request);
            serializer.Write(this.topic);
            serializer.WriteLength(this.payload);
            serializer.Write(this.payload);
        }

        public override string ToString()
        {
            return "RosUnitySrvMessageMsg: " +
            "\nsrv_id: " + srv_id.ToString() +
            "\nis_request: " + is_request.ToString() +
            "\ntopic: " + topic.ToString() +
            "\npayload: " + System.String.Join(", ", payload.ToList());
        }

        public static RosUnitySrvMessageMsg Deserialize(MessageDeserializer deserializer)
        {
            return new RosUnitySrvMessageMsg(deserializer);
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
