//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityInterfaces
{
    [Serializable]
    public class RosUnitySysCommandMsg : Message
    {
        public const string k_RosMessageName = "unity_interfaces/RosUnitySysCommand";


        public string command;
        public string params_json;

        public RosUnitySysCommandMsg()
        {
            this.command = "";
            this.params_json = "";
        }

        public RosUnitySysCommandMsg(string command, string params_json)
        {
            this.command = command;
            this.params_json = params_json;
        }

        public RosUnitySysCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command);
            deserializer.Read(out this.params_json);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
            serializer.Write(this.params_json);
        }

        public override string ToString()
        {
            return "RosUnitySysCommandMsg: " +
            "\ncommand: " + command.ToString() +
            "\nparams_json: " + params_json.ToString();
        }

        public static RosUnitySysCommandMsg Deserialize(MessageDeserializer deserializer)
        {
            return new RosUnitySysCommandMsg(deserializer);
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
