//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sensor
{
    [Serializable]
    public class SetCameraInfoRequest : Message
    {
        public const string k_RosMessageName = "sensor_msgs/SetCameraInfo";
        public override string RosMessageName => k_RosMessageName;

        //  This service requests that a camera stores the given CameraInfo as that
        //  camera's calibration information.
        // 
        //  The width and height in the camera_info field should match what the
        //  camera is currently outputting on its camera_info topic, and the camera
        //  will assume that the region of the imager that is being referred to is
        //  the region that the camera is currently capturing.
        public CameraInfoMsg camera_info;
        //  The camera_info to store

        public SetCameraInfoRequest()
        {
            this.camera_info = new CameraInfoMsg();
        }

        public SetCameraInfoRequest(CameraInfoMsg camera_info)
        {
            this.camera_info = camera_info;
        }

        public static SetCameraInfoRequest Deserialize(MessageDeserializer deserializer) => new SetCameraInfoRequest(deserializer);

        private SetCameraInfoRequest(MessageDeserializer deserializer)
        {
            this.camera_info = CameraInfoMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.camera_info);
        }

        public override string ToString()
        {
            return "SetCameraInfoRequest: " +
            "\ncamera_info: " + camera_info.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
