//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Sensor
{
    public class MTemperature : Message
    {
        public const string RosMessageName = "sensor_msgs/Temperature";

        //  Single temperature reading.
        public MHeader header;
        //  timestamp is the time the temperature was measured
        //  frame_id is the location of the temperature reading
        public double temperature;
        //  Measurement of the Temperature in Degrees Celsius
        public double variance;
        //  0 is interpreted as variance unknown

        public MTemperature()
        {
            this.header = new MHeader();
            this.temperature = 0.0;
            this.variance = 0.0;
        }

        public MTemperature(MHeader header, double temperature, double variance)
        {
            this.header = header;
            this.temperature = temperature;
            this.variance = variance;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.temperature));
            listOfSerializations.Add(BitConverter.GetBytes(this.variance));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            this.temperature = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.variance = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MTemperature: " +
            "\nheader: " + header.ToString() +
            "\ntemperature: " + temperature.ToString() +
            "\nvariance: " + variance.ToString();
        }
    }
}
