//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Sensor
{
    public class MTimeReference : Message
    {
        public const string RosMessageName = "sensor_msgs/TimeReference";

        //  Measurement from an external time source not actively synchronized with the system clock.
        public MHeader header;
        //  stamp is system time for which measurement was valid
        //  frame_id is not used 
        public MTime time_ref;
        //  corresponding time from this external source
        public string source;
        //  (optional) name of time source

        public MTimeReference()
        {
            this.header = new MHeader();
            this.time_ref = new MTime();
            this.source = "";
        }

        public MTimeReference(MHeader header, MTime time_ref, string source)
        {
            this.header = header;
            this.time_ref = time_ref;
            this.source = source;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.AddRange(time_ref.SerializationStatements());
            listOfSerializations.Add(SerializeString(this.source));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            offset = this.time_ref.Deserialize(data, offset);
            var sourceStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.source = DeserializeString(data, offset, sourceStringBytesLength);
            offset += sourceStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MTimeReference: " +
            "\nheader: " + header.ToString() +
            "\ntime_ref: " + time_ref.ToString() +
            "\nsource: " + source.ToString();
        }
    }
}
