//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.Rosgraph
{
    [Serializable]
    public class ClockMsg : Message
    {
        public const string k_RosMessageName = "rosgraph_msgs/Clock";
        public override string RosMessageName => k_RosMessageName;

        //  roslib/Clock is used for publishing simulated time in ROS. 
        //  This message simply communicates the current time.
        //  For more information, see http://www.ros.org/wiki/Clock
        public TimeMsg clock;

        public ClockMsg()
        {
            this.clock = new TimeMsg();
        }

        public ClockMsg(TimeMsg clock)
        {
            this.clock = clock;
        }

        public static ClockMsg Deserialize(MessageDeserializer deserializer) => new ClockMsg(deserializer);

        private ClockMsg(MessageDeserializer deserializer)
        {
            this.clock = TimeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.clock);
        }

        public override string ToString()
        {
            return "ClockMsg: " +
            "\nclock: " + clock.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
