//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Rosgraph
{
    [Serializable]
    public class LogMsg : Message
    {
        public const string k_RosMessageName = "rosgraph_msgs/Log";
        public override string RosMessageName => k_RosMessageName;

        // #
        // # Severity level constants
        // #
        public const sbyte DEBUG = 1; // debug level
        public const sbyte INFO = 2; // general level
        public const sbyte WARN = 4; // warning level
        public const sbyte ERROR = 8; // error level
        public const sbyte FATAL = 16; // fatal/critical level
        // #
        // # Fields
        // #
        public HeaderMsg header;
        public sbyte level;
        public string name;
        //  name of the node
        public string msg;
        //  message 
        public string file;
        //  file the message came from
        public string function;
        //  function the message came from
        public uint line;
        //  line the message came from
        public string[] topics;
        //  topic names that the node publishes

        public LogMsg()
        {
            this.header = new HeaderMsg();
            this.level = 0;
            this.name = "";
            this.msg = "";
            this.file = "";
            this.function = "";
            this.line = 0;
            this.topics = new string[0];
        }

        public LogMsg(HeaderMsg header, sbyte level, string name, string msg, string file, string function, uint line, string[] topics)
        {
            this.header = header;
            this.level = level;
            this.name = name;
            this.msg = msg;
            this.file = file;
            this.function = function;
            this.line = line;
            this.topics = topics;
        }

        public static LogMsg Deserialize(MessageDeserializer deserializer) => new LogMsg(deserializer);

        private LogMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.level);
            deserializer.Read(out this.name);
            deserializer.Read(out this.msg);
            deserializer.Read(out this.file);
            deserializer.Read(out this.function);
            deserializer.Read(out this.line);
            deserializer.Read(out this.topics, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.level);
            serializer.Write(this.name);
            serializer.Write(this.msg);
            serializer.Write(this.file);
            serializer.Write(this.function);
            serializer.Write(this.line);
            serializer.WriteLength(this.topics);
            serializer.Write(this.topics);
        }

        public override string ToString()
        {
            return "LogMsg: " +
            "\nheader: " + header.ToString() +
            "\nlevel: " + level.ToString() +
            "\nname: " + name.ToString() +
            "\nmsg: " + msg.ToString() +
            "\nfile: " + file.ToString() +
            "\nfunction: " + function.ToString() +
            "\nline: " + line.ToString() +
            "\ntopics: " + System.String.Join(", ", topics.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
