//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.Rosgraph
{
    [Serializable]
    public class TopicStatisticsMsg : Message
    {
        public const string k_RosMessageName = "rosgraph_msgs/TopicStatistics";
        public override string RosMessageName => k_RosMessageName;

        //  name of the topic
        public string topic;
        //  node id of the publisher
        public string node_pub;
        //  node id of the subscriber
        public string node_sub;
        //  the statistics apply to this time window
        public TimeMsg window_start;
        public TimeMsg window_stop;
        //  number of messages delivered during the window
        public int delivered_msgs;
        //  numbers of messages dropped during the window
        public int dropped_msgs;
        //  traffic during the window, in bytes
        public int traffic;
        //  mean/stddev/max period between two messages
        public DurationMsg period_mean;
        public DurationMsg period_stddev;
        public DurationMsg period_max;
        //  mean/stddev/max age of the message based on the
        //  timestamp in the message header. In case the
        //  message does not have a header, it will be 0.
        public DurationMsg stamp_age_mean;
        public DurationMsg stamp_age_stddev;
        public DurationMsg stamp_age_max;

        public TopicStatisticsMsg()
        {
            this.topic = "";
            this.node_pub = "";
            this.node_sub = "";
            this.window_start = new TimeMsg();
            this.window_stop = new TimeMsg();
            this.delivered_msgs = 0;
            this.dropped_msgs = 0;
            this.traffic = 0;
            this.period_mean = new DurationMsg();
            this.period_stddev = new DurationMsg();
            this.period_max = new DurationMsg();
            this.stamp_age_mean = new DurationMsg();
            this.stamp_age_stddev = new DurationMsg();
            this.stamp_age_max = new DurationMsg();
        }

        public TopicStatisticsMsg(string topic, string node_pub, string node_sub, TimeMsg window_start, TimeMsg window_stop, int delivered_msgs, int dropped_msgs, int traffic, DurationMsg period_mean, DurationMsg period_stddev, DurationMsg period_max, DurationMsg stamp_age_mean, DurationMsg stamp_age_stddev, DurationMsg stamp_age_max)
        {
            this.topic = topic;
            this.node_pub = node_pub;
            this.node_sub = node_sub;
            this.window_start = window_start;
            this.window_stop = window_stop;
            this.delivered_msgs = delivered_msgs;
            this.dropped_msgs = dropped_msgs;
            this.traffic = traffic;
            this.period_mean = period_mean;
            this.period_stddev = period_stddev;
            this.period_max = period_max;
            this.stamp_age_mean = stamp_age_mean;
            this.stamp_age_stddev = stamp_age_stddev;
            this.stamp_age_max = stamp_age_max;
        }

        public static TopicStatisticsMsg Deserialize(MessageDeserializer deserializer) => new TopicStatisticsMsg(deserializer);

        private TopicStatisticsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.topic);
            deserializer.Read(out this.node_pub);
            deserializer.Read(out this.node_sub);
            this.window_start = TimeMsg.Deserialize(deserializer);
            this.window_stop = TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.delivered_msgs);
            deserializer.Read(out this.dropped_msgs);
            deserializer.Read(out this.traffic);
            this.period_mean = DurationMsg.Deserialize(deserializer);
            this.period_stddev = DurationMsg.Deserialize(deserializer);
            this.period_max = DurationMsg.Deserialize(deserializer);
            this.stamp_age_mean = DurationMsg.Deserialize(deserializer);
            this.stamp_age_stddev = DurationMsg.Deserialize(deserializer);
            this.stamp_age_max = DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.topic);
            serializer.Write(this.node_pub);
            serializer.Write(this.node_sub);
            serializer.Write(this.window_start);
            serializer.Write(this.window_stop);
            serializer.Write(this.delivered_msgs);
            serializer.Write(this.dropped_msgs);
            serializer.Write(this.traffic);
            serializer.Write(this.period_mean);
            serializer.Write(this.period_stddev);
            serializer.Write(this.period_max);
            serializer.Write(this.stamp_age_mean);
            serializer.Write(this.stamp_age_stddev);
            serializer.Write(this.stamp_age_max);
        }

        public override string ToString()
        {
            return "TopicStatisticsMsg: " +
            "\ntopic: " + topic.ToString() +
            "\nnode_pub: " + node_pub.ToString() +
            "\nnode_sub: " + node_sub.ToString() +
            "\nwindow_start: " + window_start.ToString() +
            "\nwindow_stop: " + window_stop.ToString() +
            "\ndelivered_msgs: " + delivered_msgs.ToString() +
            "\ndropped_msgs: " + dropped_msgs.ToString() +
            "\ntraffic: " + traffic.ToString() +
            "\nperiod_mean: " + period_mean.ToString() +
            "\nperiod_stddev: " + period_stddev.ToString() +
            "\nperiod_max: " + period_max.ToString() +
            "\nstamp_age_mean: " + stamp_age_mean.ToString() +
            "\nstamp_age_stddev: " + stamp_age_stddev.ToString() +
            "\nstamp_age_max: " + stamp_age_max.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
