//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveBase
{
    [Serializable]
    public class MoveBaseFeedback : Message
    {
        public const string k_RosMessageName = "move_base_msgs/MoveBase";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseStampedMsg base_position;

        public MoveBaseFeedback()
        {
            this.base_position = new Geometry.PoseStampedMsg();
        }

        public MoveBaseFeedback(Geometry.PoseStampedMsg base_position)
        {
            this.base_position = base_position;
        }

        public static MoveBaseFeedback Deserialize(MessageDeserializer deserializer) => new MoveBaseFeedback(deserializer);

        private MoveBaseFeedback(MessageDeserializer deserializer)
        {
            this.base_position = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.base_position);
        }

        public override string ToString()
        {
            return "MoveBaseFeedback: " +
            "\nbase_position: " + base_position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
