name: Connector Unit Tests
agent:
    type: Unity::VM
    image: robotics/ci-ubuntu20:latest
    flavor: i1.medium
commands:
    - pip install unity-downloader-cli --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple --upgrade
    - unity-downloader-cli -u 2020.2.09b -c editor -c StandaloneSupport-IL2CPP -c Linux --wait --published
    - git clone git@github.cds.internal.unity3d.com:unity/utr.git utr
    - utr/utr --testproject=./TestRosTcpConnector --editor-location=./.Editor --reruncount=2 --artifacts_path=test-results --stdout-filter=minimal --extra-editor-arg="--force-d3d11 --suite=playmode --suite=editor --platform=Editor"
triggers:
    cancel_old_ci: true
    expression: |
        (pull_request.target eq "main"  AND
        NOT pull_request.push.changes.all match "**/*.md") OR
        (push.branch eq "dev" AND
        NOT push.changes.all match "**/*.md")
artifacts:
    logs:
        paths:
            - "test-results/**/*"
