//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Actionlib
{
    public class MGoalStatusArray : Message
    {
        public const string RosMessageName = "actionlib_msgs/GoalStatusArray";

        //  Stores the statuses for goals that are currently being tracked
        //  by an action server
        public MHeader header;
        public MGoalStatus[] status_list;

        public MGoalStatusArray()
        {
            this.header = new MHeader();
            this.status_list = new MGoalStatus[0];
        }

        public MGoalStatusArray(MHeader header, MGoalStatus[] status_list)
        {
            this.header = header;
            this.status_list = status_list;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());

            listOfSerializations.Add(BitConverter.GetBytes(status_list.Length));
            foreach (var entry in status_list)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);

            var status_listArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.status_list = new MGoalStatus[status_listArrayLength];
            for (var i = 0; i < status_listArrayLength; i++)
            {
                this.status_list[i] = new MGoalStatus();
                offset = this.status_list[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MGoalStatusArray: " +
            "\nheader: " + header.ToString() +
            "\nstatus_list: " + System.String.Join(", ", status_list.ToList());
        }
    }
}
