//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Map
{
    [Serializable]
    public class PointCloud2UpdateMsg : Message
    {
        public const string k_RosMessageName = "map_msgs/PointCloud2Update";
        public override string RosMessageName => k_RosMessageName;

        public const uint ADD = 0;
        public const uint DELETE = 1;
        public Std.HeaderMsg header;
        public uint type;
        //  type of update, one of ADD or DELETE
        public Sensor.PointCloud2Msg points;

        public PointCloud2UpdateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.type = 0;
            this.points = new Sensor.PointCloud2Msg();
        }

        public PointCloud2UpdateMsg(Std.HeaderMsg header, uint type, Sensor.PointCloud2Msg points)
        {
            this.header = header;
            this.type = type;
            this.points = points;
        }

        public static PointCloud2UpdateMsg Deserialize(MessageDeserializer deserializer) => new PointCloud2UpdateMsg(deserializer);

        private PointCloud2UpdateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.type);
            this.points = Sensor.PointCloud2Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.type);
            serializer.Write(this.points);
        }

        public override string ToString()
        {
            return "PointCloud2UpdateMsg: " +
            "\nheader: " + header.ToString() +
            "\ntype: " + type.ToString() +
            "\npoints: " + points.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
