//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Sensor
{
    [Serializable]
    public class JoyMsg : Message
    {
        public const string k_RosMessageName = "sensor_msgs/Joy";

        //  Reports the state of a joysticks axes and buttons.
        public HeaderMsg header;
        //  timestamp in the header is the time the data is received from the joystick
        public float[] axes;
        //  the axes measurements from a joystick
        public int[] buttons;
        //  the buttons measurements from a joystick 

        public JoyMsg()
        {
            this.header = new HeaderMsg();
            this.axes = new float[0];
            this.buttons = new int[0];
        }

        public JoyMsg(HeaderMsg header, float[] axes, int[] buttons)
        {
            this.header = header;
            this.axes = axes;
            this.buttons = buttons;
        }

        public static JoyMsg Deserialize(MessageDeserializer deserializer) => new JoyMsg(deserializer);

        private JoyMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.axes, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.buttons, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.axes);
            serializer.Write(this.axes);
            serializer.WriteLength(this.buttons);
            serializer.Write(this.buttons);
        }

        public override string ToString()
        {
            return "JoyMsg: " +
            "\nheader: " + header.ToString() +
            "\naxes: " + System.String.Join(", ", axes.ToList()) +
            "\nbuttons: " + System.String.Join(", ", buttons.ToList());
        }

        #if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
        #else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
        #endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
