//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.Sensor
{
    [Serializable]
    public class TimeReferenceMsg : Message
    {
        public const string k_RosMessageName = "sensor_msgs/TimeReference";

        //  Measurement from an external time source not actively synchronized with the system clock.
        public HeaderMsg header;
        //  stamp is system time for which measurement was valid
        //  frame_id is not used 
        public TimeMsg time_ref;
        //  corresponding time from this external source
        public string source;
        //  (optional) name of time source

        public TimeReferenceMsg()
        {
            this.header = new HeaderMsg();
            this.time_ref = new TimeMsg();
            this.source = "";
        }

        public TimeReferenceMsg(HeaderMsg header, TimeMsg time_ref, string source)
        {
            this.header = header;
            this.time_ref = time_ref;
            this.source = source;
        }

        public static TimeReferenceMsg Deserialize(MessageDeserializer deserializer) => new TimeReferenceMsg(deserializer);

        private TimeReferenceMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.time_ref = TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.source);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.time_ref);
            serializer.Write(this.source);
        }

        public override string ToString()
        {
            return "TimeReferenceMsg: " +
            "\nheader: " + header.ToString() +
            "\ntime_ref: " + time_ref.ToString() +
            "\nsource: " + source.ToString();
        }

        #if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
        #else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
        #endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
