//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Map
{
    [Serializable]
    public class GetMapROIRequest : Message
    {
        public const string k_RosMessageName = "map_msgs/GetMapROI";
        public override string RosMessageName => k_RosMessageName;

        public double x;
        public double y;
        public double l_x;
        public double l_y;

        public GetMapROIRequest()
        {
            this.x = 0.0;
            this.y = 0.0;
            this.l_x = 0.0;
            this.l_y = 0.0;
        }

        public GetMapROIRequest(double x, double y, double l_x, double l_y)
        {
            this.x = x;
            this.y = y;
            this.l_x = l_x;
            this.l_y = l_y;
        }

        public static GetMapROIRequest Deserialize(MessageDeserializer deserializer) => new GetMapROIRequest(deserializer);

        private GetMapROIRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.l_x);
            deserializer.Read(out this.l_y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.l_x);
            serializer.Write(this.l_y);
        }

        public override string ToString()
        {
            return "GetMapROIRequest: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nl_x: " + l_x.ToString() +
            "\nl_y: " + l_y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
