//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Map
{
    [Serializable]
    public class ProjectedMapsInfoRequest : Message
    {
        public const string k_RosMessageName = "map_msgs/ProjectedMapsInfo";

        public ProjectedMapInfoMsg[] projected_maps_info;

        public ProjectedMapsInfoRequest()
        {
            this.projected_maps_info = new ProjectedMapInfoMsg[0];
        }

        public ProjectedMapsInfoRequest(ProjectedMapInfoMsg[] projected_maps_info)
        {
            this.projected_maps_info = projected_maps_info;
        }

        public static ProjectedMapsInfoRequest Deserialize(MessageDeserializer deserializer) => new ProjectedMapsInfoRequest(deserializer);

        private ProjectedMapsInfoRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.projected_maps_info, ProjectedMapInfoMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.projected_maps_info);
            serializer.Write(this.projected_maps_info);
        }

        public override string ToString()
        {
            return "ProjectedMapsInfoRequest: " +
            "\nprojected_maps_info: " + System.String.Join(", ", projected_maps_info.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
