//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Map
{
    [Serializable]
    public class SaveMapRequest : Message
    {
        public const string k_RosMessageName = "map_msgs/SaveMap";
        public override string RosMessageName => k_RosMessageName;

        //  Save the map to the filesystem
        public Std.StringMsg filename;

        public SaveMapRequest()
        {
            this.filename = new Std.StringMsg();
        }

        public SaveMapRequest(Std.StringMsg filename)
        {
            this.filename = filename;
        }

        public static SaveMapRequest Deserialize(MessageDeserializer deserializer) => new SaveMapRequest(deserializer);

        private SaveMapRequest(MessageDeserializer deserializer)
        {
            this.filename = Std.StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.filename);
        }

        public override string ToString()
        {
            return "SaveMapRequest: " +
            "\nfilename: " + filename.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
