//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Map
{
    [Serializable]
    public class SetMapProjectionsRequest : Message
    {
        public const string k_RosMessageName = "map_msgs/SetMapProjections";
        public override string RosMessageName => k_RosMessageName;


        public SetMapProjectionsRequest()
        {
        }
        public static SetMapProjectionsRequest Deserialize(MessageDeserializer deserializer) => new SetMapProjectionsRequest(deserializer);

        private SetMapProjectionsRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "SetMapProjectionsRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
