//Do not edit! This file was generated by Unity-ROS MessageGeneration. Better now!
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geometry
{
    public class MVector3 : Message
    {
        public const string RosMessageName = "geometry_msgs/Vector3";

        //  This represents a vector in free space.
        //  This is semantically different than a point.
        //  A vector is always anchored at the origin.
        //  When a transform is applied to a vector, only the rotational component is applied.
        public double x;
        public double y;
        public double z;

        public MVector3()
        {
            this.x = 0.0;
            this.y = 0.0;
            this.z = 0.0;
        }

        public MVector3(double x, double y, double z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.x));
            listOfSerializations.Add(BitConverter.GetBytes(this.y));
            listOfSerializations.Add(BitConverter.GetBytes(this.z));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.x = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.y = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.z = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MVector3: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString();
        }
    }
}
