//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosTcpEndpoint
{
    public class MRosUnityTopicListRequest : Message
    {
        public const string k_RosMessageName = "ROS_TCP_Endpoint/RosUnityTopicList";
        public override string RosMessageName => k_RosMessageName;


        public MRosUnityTopicListRequest()
        {
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {

            return offset;
        }

        public override string ToString()
        {
            return "MRosUnityTopicListRequest: ";
        }
    }
}
