//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosTcpEndpoint
{
    public class MUnityHandshakeResponse : Message
    {
        public const string k_RosMessageName = "ROS_TCP_Endpoint/UnityHandshake";
        public override string RosMessageName => k_RosMessageName;

        public string ip;

        public MUnityHandshakeResponse()
        {
            this.ip = "";
        }

        public MUnityHandshakeResponse(string ip)
        {
            this.ip = ip;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.ip));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var ipStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.ip = DeserializeString(data, offset, ipStringBytesLength);
            offset += ipStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MUnityHandshakeResponse: " +
            "\nip: " + ip.ToString();
        }
    }
}
