//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Std
{
    public class MTime : Message
    {
        public const string k_RosMessageName = "std_msgs/Time";
        public override string RosMessageName => k_RosMessageName;

        public uint secs;
        public uint nsecs;

        public MTime()
        {
            secs = 0;
            nsecs = 0;
        }

        public MTime(uint secs, uint nsecs)
        {
            this.secs = secs;
            this.nsecs = nsecs;
        }

        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.secs));
            listOfSerializations.Add(BitConverter.GetBytes(this.nsecs));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.secs = BitConverter.ToUInt32(data, offset);
            offset += 4;
            this.nsecs = BitConverter.ToUInt32(data, offset);
            offset += 4;

            return offset;
        }
    }
}
