//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosTcpEndpoint
{
    public class RosUnitySysCommand : Message
    {
        public const string RosMessageName = "ros_tcp_endpoint/RosUnitySysCommand";

        public string command;
        public string params_json;

        public RosUnitySysCommand()
        {
            this.command = "";
            this.params_json = "";
        }

        public RosUnitySysCommand(string command, string params_json)
        {
            this.command = command;
            this.params_json = params_json;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.command));
            listOfSerializations.Add(SerializeString(this.params_json));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var commandStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.command = DeserializeString(data, offset, commandStringBytesLength);
            offset += commandStringBytesLength;
            var params_jsonStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.params_json = DeserializeString(data, offset, params_jsonStringBytesLength);
            offset += params_jsonStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "RosUnitySysCommand: " +
            "\ncommand: " + command.ToString() +
            "\nparams_json: " + params_json.ToString();
        }
    }
}
