//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ObjectRecognition
{
    public class ObjectRecognitionFeedback : Message
    {
        public const string RosMessageName = "object_recognition_msgs-master/ObjectRecognition";

        // no feedback

        public ObjectRecognitionFeedback()
        {
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {

            return offset;
        }

        public override string ToString()
        {
            return "ObjectRecognitionFeedback: ";
        }
    }
}
