//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav
{
    public class MGetPlanResponse : Message
    {
        public const string RosMessageName = "nav_msgs/GetPlan";

        public MPath plan;

        public MGetPlanResponse()
        {
            this.plan = new MPath();
        }

        public MGetPlanResponse(MPath plan)
        {
            this.plan = plan;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(plan.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.plan.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MGetPlanResponse: " +
            "\nplan: " + plan.ToString();
        }
    }
}
