//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav
{
    [Serializable]
    public class SetMapRequest : Message
    {
        public const string k_RosMessageName = "nav_msgs/SetMap";
        public override string RosMessageName => k_RosMessageName;

        //  Set a new map together with an initial pose
        //  Requested 2D map to be set.
        public OccupancyGridMsg map;
        //  Estimated initial pose when setting new map.
        public Geometry.PoseWithCovarianceStampedMsg initial_pose;

        public SetMapRequest()
        {
            this.map = new OccupancyGridMsg();
            this.initial_pose = new Geometry.PoseWithCovarianceStampedMsg();
        }

        public SetMapRequest(OccupancyGridMsg map, Geometry.PoseWithCovarianceStampedMsg initial_pose)
        {
            this.map = map;
            this.initial_pose = initial_pose;
        }

        public static SetMapRequest Deserialize(MessageDeserializer deserializer) => new SetMapRequest(deserializer);

        private SetMapRequest(MessageDeserializer deserializer)
        {
            this.map = OccupancyGridMsg.Deserialize(deserializer);
            this.initial_pose = Geometry.PoseWithCovarianceStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.map);
            serializer.Write(this.initial_pose);
        }

        public override string ToString()
        {
            return "SetMapRequest: " +
            "\nmap: " + map.ToString() +
            "\ninitial_pose: " + initial_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
