//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Std
{
    public class MUInt16MultiArray : Message
    {
        public const string RosMessageName = "std_msgs/UInt16MultiArray";

        //  Please look at the MultiArrayLayout message definition for
        //  documentation on all multiarrays.
        public MMultiArrayLayout layout;
        //  specification of data layout
        public ushort[] data;
        //  array of data

        public MUInt16MultiArray()
        {
            this.layout = new MMultiArrayLayout();
            this.data = new ushort[0];
        }

        public MUInt16MultiArray(MMultiArrayLayout layout, ushort[] data)
        {
            this.layout = layout;
            this.data = data;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(layout.SerializationStatements());

            listOfSerializations.Add(BitConverter.GetBytes(data.Length));
            foreach (var entry in data)
                listOfSerializations.Add(BitConverter.GetBytes(entry));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.layout.Deserialize(data, offset);

            var dataArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.data = new ushort[dataArrayLength];
            for (var i = 0; i < dataArrayLength; i++)
            {
                this.data[i] = BitConverter.ToUInt16(data, offset);
                offset += 2;
            }

            return offset;
        }

        public override string ToString()
        {
            return "MUInt16MultiArray: " +
            "\nlayout: " + layout.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }
    }
}
