//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Std
{
    [Serializable]
    public class MultiArrayDimensionMsg : Message
    {
        public const string k_RosMessageName = "std_msgs/MultiArrayDimension";
        public override string RosMessageName => k_RosMessageName;

        //  This was originally provided as an example message.
        //  It is deprecated as of Foxy
        //  It is recommended to create your own semantically meaningful message.
        //  However if you would like to continue using this please use the equivalent in example_msgs.
        public string label;
        //  label of given dimension
        public uint size;
        //  size of given dimension (in type units)
        public uint stride;
        //  stride of given dimension

        public MultiArrayDimensionMsg()
        {
            this.label = "";
            this.size = 0;
            this.stride = 0;
        }

        public MultiArrayDimensionMsg(string label, uint size, uint stride)
        {
            this.label = label;
            this.size = size;
            this.stride = stride;
        }

        public static MultiArrayDimensionMsg Deserialize(MessageDeserializer deserializer) => new MultiArrayDimensionMsg(deserializer);

        private MultiArrayDimensionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.label);
            deserializer.Read(out this.size);
            deserializer.Read(out this.stride);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.label);
            serializer.Write(this.size);
            serializer.Write(this.stride);
        }

        public override string ToString()
        {
            return "MultiArrayDimensionMsg: " +
            "\nlabel: " + label.ToString() +
            "\nsize: " + size.ToString() +
            "\nstride: " + stride.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
